name: SAST scan in different folders of the Repo

on:
  pull_request:
    types: [opened, reopened, synchronize] 
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run PowerShell Hello
      run: |
        pwsh -Command "Write-Host 'Hello from PowerShell!'"
    
    - name: Download ZIP file
      run: |
        $url = "https://download.checkmarx.com/9.5.0/Plugins/CxConsolePlugin-1.1.30.zip"
        $outputFile = "$env:GITHUB_WORKSPACE/CxConsolePlugin-1.1.30.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
    
    - name: Unzip file
      run: |
        $zipFile = "$env:GITHUB_WORKSPACE/CxConsolePlugin-1.1.30.zip"
        $destinationFolder = "$env:GITHUB_WORKSPACE/CxConsolePlugin-1.1.30"
        Expand-Archive -Path $zipFile -DestinationPath $destinationFolder -Force
    
    - name: Run CLI
      run: |
        $server = "${{ secrets.CHECKMARX_SERVER }}"
        $projectName = "${{ secrets.CHECKMARX_PROJECT }}"
        $username = "${{ secrets.CHECKMARX_USERNAME }}"
        $password = "${{ secrets.CHECKMARX_PASSWORD }}"
        $folders = @("testMonorepo1", "testMonorepo2")

        foreach ($folder in $folders) {
          $cliPath = "$env:GITHUB_WORKSPACE\CxConsolePlugin-1.1.30"
          $cliExecutable = "runCxConsole.cmd"
          
          # Build the arguments array
          $args = @(
            "Scan", 
            "-CxServer", $server, 
            "-v", 
            "-ProjectName", "$projectName/$folder", 
            "-LocationType", "folder",
            "-LocationPath", "$env:GITHUB_WORKSPACE\$folder",
            "-cxuser", $username, 
            "-cxpassword", $password, 
            "-preset", "Checkmarx Default"
          )

          # Debug output
          Write-Host "Running command: & `"$cliPath\$cliExecutable`" $($args -join ' ')"

          # Run the CLI command
          & "$cliPath\$cliExecutable" $args
        }
